require:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - ./custom_cops/nxt_core/rails/use_of_rails_logger.rb

Rails/UseOfRailsLogger:
  Description: "Custom Getsafe cop to ensure the correct logger is used"
  Enabled: true
