AllCops:
  Exclude:
    # generated files
    - bin/guard
    - bin/rspec
    - bin/rubocop
    - bin/setup
    - config.ru
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - node_modules/**/*
  TargetRubyVersion: 2.6
  DisabledByDefault: true
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/SpaceBeforeBlockBraces:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Lint:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/Loop:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessTimes:
  Enabled: true
Style/MutableConstant:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
Style/WordArray:
  Enabled: true
Security:
  Enabled: true
Style/Semicolon:
  Exclude:
    - spec/**/*
