AllCops:
  Exclude:
    # generated files
    - bin/guard
    - bin/rspec
    - bin/rubocop
    - bin/setup
    - config.ru
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - node_modules/**/*
  TargetRubyVersion: 2.6
  DisabledByDefault: true
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Lint:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/Loop:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true
Style/WordArray:
  Enabled: true
Security:
  Enabled: true
Style/Semicolon:
  Exclude:
    - spec/**/*
